name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - alpha
  pull_request:
    branches:
      - master
      - alpha

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: pip install flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          flake8_args: "--max-line-length 120 --exclude oss_licenses.py --ignore=E203,E129,E123,W503,W504,E125,E126"
